NATIONALITIES = {'AF': {'country_name': 'Afghanistan', 'nationality': 'Afghan'},
                 'AX': {'country_name': 'Åland Islands', 'nationality': 'Åland Island'},
                 'AL': {'country_name': 'Albania', 'nationality': 'Albanian'},
                 'DZ': {'country_name': 'Algeria', 'nationality': 'Algerian'},
                 'AS': {'country_name': 'American Samoa', 'nationality': 'American Samoan'},
                 'AD': {'country_name': 'Andorra', 'nationality': 'Andorran'},
                 'AO': {'country_name': 'Angola', 'nationality': 'Angolan'},
                 'AI': {'country_name': 'Anguilla', 'nationality': 'Anguillan'},
                 'AQ': {'country_name': 'Antarctica', 'nationality': 'Antarctic'},
                 'AG': {'country_name': 'Antigua and Barbuda', 'nationality': 'Antiguans'},
                 'AR': {'country_name': 'Argentina', 'nationality': 'Argentine'},
                 'AM': {'country_name': 'Armenia', 'nationality': 'Armenian'},
                 'AW': {'country_name': 'Aruba', 'nationality': 'Aruban'},
                 'AU': {'country_name': 'Australia', 'nationality': 'Aussie'},
                 'AT': {'country_name': 'Austria', 'nationality': 'Austrian'},
                 'AZ': {'country_name': 'Azerbaijan', 'nationality': 'Azerbaijani'},
                 'BS': {'country_name': 'Bahamas', 'nationality': 'Bahamian'},
                 'BH': {'country_name': 'Bahrain', 'nationality': 'Bahraini'},
                 'BD': {'country_name': 'Bangladesh', 'nationality': 'Bangladeshi'},
                 'BB': {'country_name': 'Barbados', 'nationality': 'Bajan'},
                 'BY': {'country_name': 'Belarus', 'nationality': 'Belarusian'},
                 'BE': {'country_name': 'Belgium', 'nationality': 'Belgian'},
                 'BZ': {'country_name': 'Belize', 'nationality': 'Belizean'},
                 'BJ': {'country_name': 'Benin', 'nationality': 'Beninois'},
                 'BM': {'country_name': 'Bermuda', 'nationality': 'Bermudan'},
                 'BT': {'country_name': 'Bhutan', 'nationality': 'Bhutanese'},
                 'BO': {'country_name': 'Bolivia', 'nationality': 'Bolivian'},
                 'BQ': {'country_name': 'Bonaire, Sint Eustatius and Saba', 'nationality': 'Bonaire'},
                 'BA': {'country_name': 'Bosnia and Herzegovina', 'nationality': 'Bosnian'},
                 'BW': {'country_name': 'Botswana', 'nationality': 'Batswana'},
                 'BV': {'country_name': 'Bouvet Island', 'nationality': 'Bouvet Island'},
                 'BR': {'country_name': 'Brazil', 'nationality': 'Brasileiro'},
                 'IO': {'country_name': 'British Indian Ocean Territory', 'nationality': 'Biot'},
                 'BN': {'country_name': 'Brunei', 'nationality': 'Bruneian'},
                 'BG': {'country_name': 'Bulgaria', 'nationality': 'Bulgarian'},
                 'BF': {'country_name': 'Burkina Faso', 'nationality': 'Burkinabe'},
                 'BI': {'country_name': 'Burundi', 'nationality': 'Burundian'},
                 'CV': {'country_name': 'Cabo Verde', 'nationality': 'Cabo Verdean'},
                 'KH': {'country_name': 'Cambodia', 'nationality': 'Cambodian'},
                 'CM': {'country_name': 'Cameroon', 'nationality': 'Cameroonian'},
                 'CA': {'country_name': 'Canada', 'nationality': 'Canadian'},
                 'KY': {'country_name': 'Cayman Islands', 'nationality': 'Caymanian'},
                 'CF': {'country_name': 'Central African Republic', 'nationality': 'Central African'},
                 'TD': {'country_name': 'Chad', 'nationality': 'Chadian'},
                 'CL': {'country_name': 'Chile', 'nationality': 'Chilean'},
                 'CN': {'country_name': 'China', 'nationality': 'Chinese'},
                 'CX': {'country_name': 'Christmas Island', 'nationality': 'Christmas Island'},
                 'CC': {'country_name': 'Cocos (Keeling) Islands', 'nationality': 'Cocos Islander'},
                 'CO': {'country_name': 'Colombia', 'nationality': 'Colombian'},
                 'KM': {'country_name': 'Comoros', 'nationality': 'Comoran'},
                 'CG': {'country_name': 'Congo', 'nationality': 'Congolese'},
                 'CD': {'country_name': 'Congo', 'nationality': 'Congolese'},
                 'CK': {'country_name': 'Cook Islands', 'nationality': 'Cook Island'},
                 'CR': {'country_name': 'Costa Rica', 'nationality': 'Costa Rican'},
                 'CI': {'country_name': "Côte d'Ivoire", 'nationality': ''},
                 'HR': {'country_name': 'Croatia', 'nationality': 'Croat'},
                 'CU': {'country_name': 'Cuba', 'nationality': 'Cuban'},
                 'CW': {'country_name': 'Curaçao', 'nationality': 'Curaçaoan'},
                 'CY': {'country_name': 'Cyprus', 'nationality': 'Cypriot'},
                 'CZ': {'country_name': 'Czechia', 'nationality': 'Czech'},
                 'DK': {'country_name': 'Denmark', 'nationality': 'Dane'},
                 'DJ': {'country_name': 'Djibouti', 'nationality': 'Djibouti'},
                 'DM': {'country_name': 'Dominica', 'nationality': 'Dominican'},
                 'DO': {'country_name': 'Dominican Republic', 'nationality': 'Dominican'},
                 'EC': {'country_name': 'Ecuador', 'nationality': 'Ecuadorian'},
                 'EG': {'country_name': 'Egypt', 'nationality': 'Egyptian'},
                 'SV': {'country_name': 'El Salvador', 'nationality': 'Salvadoran'},
                 'GQ': {'country_name': 'Equatorial Guinea', 'nationality': 'Equatoguinean'},
                 'ER': {'country_name': 'Eritrea', 'nationality': 'Eritrean'},
                 'EE': {'country_name': 'Estonia', 'nationality': 'Estonian'},
                 'SZ': {'country_name': 'Eswatini', 'nationality': ''},
                 'ET': {'country_name': 'Ethiopia', 'nationality': 'Ethiopian'},
                 'FK': {'country_name': 'Falkland Islands (Malvinas)', 'nationality': ''},
                 'FO': {'country_name': 'Faroe Islands', 'nationality': 'Faroese'},
                 'FJ': {'country_name': 'Fiji', 'nationality': 'Fijian'},
                 'FI': {'country_name': 'Finland', 'nationality': 'Finn'},
                 'FR': {'country_name': 'France', 'nationality': 'French'},
                 'GF': {'country_name': 'French Guiana', 'nationality': 'French Guianese'},
                 'PF': {'country_name': 'French Polynesia', 'nationality': 'French Polynesian'},
                 'TF': {'country_name': 'French Southern Territories', 'nationality': 'French Southern Territories'},
                 'GA': {'country_name': 'Gabon', 'nationality': 'Gabonese'},
                 'GM': {'country_name': 'Gambia', 'nationality': 'Gambian'},
                 'GE': {'country_name': 'Georgia', 'nationality': 'Buzzard'},
                 'DE': {'country_name': 'Germany', 'nationality': 'German'},
                 'GH': {'country_name': 'Ghana', 'nationality': 'Ghanaian'},
                 'GI': {'country_name': 'Gibraltar', 'nationality': 'Gibraltar'},
                 'GR': {'country_name': 'Greece', 'nationality': 'Greek'},
                 'GL': {'country_name': 'Greenland', 'nationality': 'Greenlandic'},
                 'GD': {'country_name': 'Grenada', 'nationality': 'Grenadian'},
                 'GP': {'country_name': 'Guadeloupe', 'nationality': 'Guadeloupe'},
                 'GU': {'country_name': 'Guam', 'nationality': 'Guamanian'},
                 'GT': {'country_name': 'Guatemala', 'nationality': 'Guatemalan'},
                 'GG': {'country_name': 'Guernsey', 'nationality': 'Channel Island'},
                 'GN': {'country_name': 'Guinea', 'nationality': 'Guinean'},
                 'GW': {'country_name': 'Guinea-Bissau', 'nationality': 'Bissau-Guinean'},
                 'GY': {'country_name': 'Guyana', 'nationality': 'Guyanese'},
                 'HT': {'country_name': 'Haiti', 'nationality': 'Haitian'},
                 'HM': {'country_name': 'Head Island', 'nationality': ''},
                 'VA': {'country_name': 'Holy See', 'nationality': ''},
                 'HN': {'country_name': 'Honduras', 'nationality': 'Honduran'},
                 'HK': {'country_name': 'Hong Kong', 'nationality': 'Hong Kong'},
                 'HU': {'country_name': 'Hungary', 'nationality': 'Hungarian'},
                 'IS': {'country_name': 'Iceland', 'nationality': 'Icelandic'},
                 'IN': {'country_name': 'India', 'nationality': 'Indian'},
                 'ID': {'country_name': 'Indonesia', 'nationality': 'Indonesian'},
                 'IR': {'country_name': 'Iran', 'nationality': 'Irani'},
                 'IQ': {'country_name': 'Iraq', 'nationality': 'Iraqi'},
                 'IE': {'country_name': 'Ireland', 'nationality': 'Irish'},
                 'IM': {'country_name': 'Isle of Man', 'nationality': 'Manxwoman'},
                 'IL': {'country_name': 'Israel', 'nationality': 'Israeli'},
                 'IT': {'country_name': 'Italy', 'nationality': 'Italian'},
                 'JM': {'country_name': 'Jamaica', 'nationality': 'Jamaican'},
                 'JP': {'country_name': 'Japan', 'nationality': 'Japanese'},
                 'JE': {'country_name': 'Jersey', 'nationality': 'Jerseyan'},
                 'JO': {'country_name': 'Jordan', 'nationality': 'Jordanian'},
                 'KZ': {'country_name': 'Kazakhstan', 'nationality': 'Kazakhstani'},
                 'KE': {'country_name': 'Kenya', 'nationality': 'Kenyan'},
                 'KI': {'country_name': 'Kiribati', 'nationality': 'I-Kiribati'},
                 'KW': {'country_name': 'Kuwait', 'nationality': 'Kuwaiti'},
                 'KG': {'country_name': 'Kyrgyzstan', 'nationality': 'Kyrgyz'},
                 'LA': {'country_name': 'Laos', 'nationality': 'Lao'},
                 'LV': {'country_name': 'Latvia', 'nationality': 'Latvian'},
                 'LB': {'country_name': 'Lebanon', 'nationality': 'Lebanese'},
                 'LS': {'country_name': 'Lesotho', 'nationality': 'Basotho'},
                 'LR': {'country_name': 'Liberia', 'nationality': 'Liberian'},
                 'LY': {'country_name': 'Libya', 'nationality': 'Libyan'},
                 'LI': {'country_name': 'Liechtenstein', 'nationality': 'Liechtenstein'},
                 'LT': {'country_name': 'Lithuania', 'nationality': 'Lithuanian'},
                 'LU': {'country_name': 'Luxembourg', 'nationality': 'Luxembourg'},
                 'MO': {'country_name': 'Macao', 'nationality': ''},
                 'MG': {'country_name': 'Madagascar', 'nationality': 'Malagasy'},
                 'MW': {'country_name': 'Malawi', 'nationality': 'Malawian'},
                 'MY': {'country_name': 'Malaysia', 'nationality': 'Malaysian'},
                 'MV': {'country_name': 'Maldives', 'nationality': 'Maldivian'},
                 'ML': {'country_name': 'Mali', 'nationality': 'Malian'},
                 'MT': {'country_name': 'Malta', 'nationality': 'Maltese'},
                 'MH': {'country_name': 'Marshall Islands', 'nationality': 'Marshallese'},
                 'MQ': {'country_name': 'Martinique', 'nationality': 'Martinican'},
                 'MR': {'country_name': 'Mauritania', 'nationality': 'Mauritanian'},
                 'MU': {'country_name': 'Mauritius', 'nationality': 'Mauritian'},
                 'YT': {'country_name': 'Mayotte', 'nationality': 'Mahorais'},
                 'MX': {'country_name': 'Mexico', 'nationality': 'Mexican'},
                 'FM': {'country_name': 'Micronesia', 'nationality': 'Micronesian'},
                 'MD': {'country_name': 'Moldova', 'nationality': 'Moldovan'},
                 'MC': {'country_name': 'Monaco', 'nationality': 'Monacan'},
                 'MN': {'country_name': 'Mongolia', 'nationality': 'Mongol'},
                 'ME': {'country_name': 'Montenegro', 'nationality': 'Montenegrin'},
                 'MS': {'country_name': 'Montserrat', 'nationality': 'Montserratian'},
                 'MA': {'country_name': 'Morocco', 'nationality': 'Moroccan'},
                 'MZ': {'country_name': 'Mozambique', 'nationality': 'Mozambican'},
                 'MM': {'country_name': 'Myanmar', 'nationality': 'Myanmarese'},
                 'NA': {'country_name': 'Namibia', 'nationality': 'Namibian'},
                 'NR': {'country_name': 'Nauru', 'nationality': 'Nauruan'},
                 'NP': {'country_name': 'Nepal', 'nationality': 'Gurkhas'},
                 'NL': {'country_name': 'Netherlands', 'nationality': 'Dutch'},
                 'NC': {'country_name': 'New Caledonia', 'nationality': 'New Caledonian'},
                 'NZ': {'country_name': 'New Zealand', 'nationality': 'Kiwi'},
                 'NI': {'country_name': 'Nicaragua', 'nationality': 'Nicaraguan'},
                 'NE': {'country_name': 'Niger', 'nationality': 'Nigerien'},
                 'NG': {'country_name': 'Nigeria', 'nationality': 'Nigerian'},
                 'NU': {'country_name': 'Niue', 'nationality': 'Niuean'},
                 'NF': {'country_name': 'Norfolk Island', 'nationality': 'Norfolk Island'},
                 'KP': {'country_name': 'North Korea', 'nationality': 'North Korean'},
                 'MK': {'country_name': 'North Macedonia', 'nationality': 'Macedonian'},
                 'MP': {'country_name': 'Northern Mariana Islands', 'nationality': 'Northern Marianan'},
                 'NO': {'country_name': 'Norway', 'nationality': 'Nordmann'},
                 'OM': {'country_name': 'Oman', 'nationality': 'Omani'},
                 'PK': {'country_name': 'Pakistan', 'nationality': 'Pakistani'},
                 'PW': {'country_name': 'Palau', 'nationality': 'Palauan'},
                 'PS': {'country_name': 'Palestine, State of', 'nationality': 'Palestinian'},
                 'PA': {'country_name': 'Panama', 'nationality': 'Panamanian'},
                 'PG': {'country_name': 'Papua New Guinea', 'nationality': 'Papua New Guinean'},
                 'PY': {'country_name': 'Paraguay', 'nationality': 'Paraguayan'},
                 'PE': {'country_name': 'Peru', 'nationality': 'Peruvian'},
                 'PH': {'country_name': 'Philippines', 'nationality': 'Filipino'},
                 'PN': {'country_name': 'Pitcairn', 'nationality': 'Pitcairnians'},
                 'PL': {'country_name': 'Poland', 'nationality': 'Pole'},
                 'PT': {'country_name': 'Portugal', 'nationality': 'Portuguese'},
                 'PR': {'country_name': 'Puerto Rico', 'nationality': 'Boricua'},
                 'QA': {'country_name': 'Qatar', 'nationality': 'Qatari'},
                 'RE': {'country_name': 'Réunion', 'nationality': 'Réunionese'},
                 'RO': {'country_name': 'Romania', 'nationality': 'Romanian'},
                 'RU': {'country_name': 'Russia', 'nationality': 'Russian'},
                 'RW': {'country_name': 'Rwanda', 'nationality': 'Rwandan'},
                 'BL': {'country_name': 'Saint Barthélemy', 'nationality': 'Barthélemois'},
                 'SH': {'country_name': 'Saint Helena', 'nationality': 'Saint Helenian'},
                 'KN': {'country_name': 'Saint Kitts and Nevis', 'nationality': 'Kittian'},
                 'LC': {'country_name': 'Saint Lucia', 'nationality': 'Saint Lucian'},
                 'MF': {'country_name': 'Saint Martin (French part)', 'nationality': ''},
                 'PM': {'country_name': 'Saint Pierre and Miquelon', 'nationality': 'Miquelonnais'},
                 'VC': {'country_name': 'Saint Vincent and the Grenadines', 'nationality': ''},
                 'WS': {'country_name': 'Samoa', 'nationality': 'Samoan'},
                 'SM': {'country_name': 'San Marino', 'nationality': 'Sammarinese'},
                 'ST': {'country_name': 'Sao Tome and Principe', 'nationality': 'Sao Tomean'},
                 'SA': {'country_name': 'Saudi Arabia', 'nationality': 'Saudi'},
                 'SN': {'country_name': 'Senegal', 'nationality': 'Senegalese'},
                 'RS': {'country_name': 'Serbia', 'nationality': 'Serb'},
                 'SC': {'country_name': 'Seychelles', 'nationality': 'Seychellois'},
                 'SL': {'country_name': 'Sierra Leone', 'nationality': 'Sierra Leonean'},
                 'SG': {'country_name': 'Singapore', 'nationality': 'Singapore'},
                 'SX': {'country_name': 'Sint Maarten (Dutch part)', 'nationality': ''},
                 'SK': {'country_name': 'Slovakia', 'nationality': 'Slovak'},
                 'SI': {'country_name': 'Slovenia', 'nationality': 'Slovene'},
                 'SB': {'country_name': 'Solomon Islands', 'nationality': 'Solomon Island'},
                 'SO': {'country_name': 'Somalia', 'nationality': 'Somali'},
                 'ZA': {'country_name': 'South Africa', 'nationality': 'South African'},
                 'GS': {'country_name': 'South Georgia', 'nationality': ''},
                 'KR': {'country_name': 'South Korea', 'nationality': 'South Korean'},
                 'SS': {'country_name': 'South Sudan', 'nationality': 'South Sudanese'},
                 'ES': {'country_name': 'Spain', 'nationality': 'Spaniard'},
                 'LK': {'country_name': 'Sri Lanka', 'nationality': 'Sri Lankan'},
                 'SD': {'country_name': 'Sudan', 'nationality': 'Sudanese'},
                 'SR': {'country_name': 'Suriname', 'nationality': 'Surinamer'},
                 'SJ': {'country_name': 'Svalbard and Jan Mayen', 'nationality': ''},
                 'SE': {'country_name': 'Sweden', 'nationality': 'Swede'},
                 'CH': {'country_name': 'Switzerland', 'nationality': 'Swiss'},
                 'SY': {'country_name': 'Syria', 'nationality': 'Syrian'},
                 'TW': {'country_name': 'Taiwan', 'nationality': 'Taiwanese'},
                 'TJ': {'country_name': 'Tajikistan', 'nationality': 'Tadzhik'},
                 'TZ': {'country_name': 'Tanzania', 'nationality': 'Tanzanian'},
                 'TH': {'country_name': 'Thailand', 'nationality': 'Thai'},
                 'TL': {'country_name': 'Timor-Leste', 'nationality': 'Timorese'},
                 'TG': {'country_name': 'Togo', 'nationality': 'Togolese'},
                 'TK': {'country_name': 'Tokelau', 'nationality': 'Tokelauan'},
                 'TO': {'country_name': 'Tonga', 'nationality': 'Tongan'},
                 'TT': {'country_name': 'Trinidad and Tobago', 'nationality': 'Tobagonian'},
                 'TN': {'country_name': 'Tunisia', 'nationality': 'Tunisian'},
                 'TR': {'country_name': 'Türkiye', 'nationality': 'Turkish'},
                 'TM': {'country_name': 'Turkmenistan', 'nationality': 'Turkmen'},
                 'TC': {'country_name': 'Turks and Caicos Islands', 'nationality': 'Turks And Caicos Island'},
                 'TV': {'country_name': 'Tuvalu', 'nationality': 'Tuvaluan'},
                 'UG': {'country_name': 'Uganda', 'nationality': 'Ugandan'},
                 'UA': {'country_name': 'Ukraine', 'nationality': 'Ukrainian'},
                 'AE': {'country_name': 'United Arab Emirates', 'nationality': 'Emirati'},
                 'GB': {'country_name': 'United Kingdom', 'nationality': 'British'},
                 'US': {'country_name': 'United States of America', 'nationality': 'American'},
                 'UY': {'country_name': 'Uruguay', 'nationality': 'Uruguayan'},
                 'UM': {'country_name': 'US Minor Outlying Islands', 'nationality': ''},
                 'UZ': {'country_name': 'Uzbekistan', 'nationality': 'Uzbek'},
                 'VU': {'country_name': 'Vanuatu', 'nationality': 'Ni-Vanuatu'},
                 'VE': {'country_name': 'Venezuela', 'nationality': 'Venezuelan'},
                 'VN': {'country_name': 'Vietnam', 'nationality': 'Vietnamese'},
                 'VG': {'country_name': 'Virgin Islands (British)', 'nationality': ''},
                 'VI': {'country_name': 'Virgin Islands (U.S.)', 'nationality': ''},
                 'WF': {'country_name': 'Wallis and Futuna', 'nationality': 'Futunan'},
                 'EH': {'country_name': 'Western Sahara', 'nationality': 'Sahraoui'},
                 'YE': {'country_name': 'Yemen', 'nationality': 'Yemeni'},
                 'ZM': {'country_name': 'Zambia', 'nationality': 'Zambian'},
                 'ZW': {'country_name': 'Zimbabwe', 'nationality': 'Zimbabwean'}}
